---
## cSpell:disable
## Copied from: rasa/dotfiles/.github/.cspell/ignore-paths.yml
## EDIT THE ABOVE FILE OR YOUR CHANGES WILL BE LOST!
## Manually curated list of paths/files to not spellcheck

ignorePaths:
  - path/to/file1
  - path/to/file2
