---
## cSpell:disable
## Copied from: rasa/dotfiles/.github/.cspell/incorrect-words.yml
## EDIT THE ABOVE FILE OR YOUR CHANGES WILL BE LOST!
# Manually curated list of words to treat as incorrectly spelled

flagWords:
  - notaword1
  - notaword2
