version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "08:30"
      timezone: "America/Los_Angeles"
    # labels:
    #  - "dependency"
    reviewers:
      - "rasa"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:30"
      timezone: "America/Los_Angeles"
    # labels:
    #  - "dependency"
    reviewers:
      - "rasa"
