# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

APPLY_FIXES: all
DISABLE:
  - SPELL # Uncomment to disable checks of spelling mistakes
# PRINT_ALL_FILES: false
# SHOW_ELAPSED_TIME: true
# EMAIL_REPORTER: false
# FILEIO_REPORTER: true
# JSON_REPORTER: true
# GITHUB_STATUS_REPORTER: false
