---
# yamllint disable rule:line-length
# $schema https://raw.githubusercontent.com/megalinter/megalinter/main/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
# ~/.mega-linter.yml
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/configuration/ and in linters documentation

EXTENDS: https://raw.githubusercontent.com/rasa/rasa/refs/heads/master/.github/mega-linter-shared.yml

## FILTERS ##

# FILTER_REGEX_EXCLUDE: >-
#   (?ix)(
#   megalinter-reports
#   \.git
#   )/"

## CONVERT ERRORS TO WARNINGS ##

# quiets:
#   Check: CKV2_GHA_1: "Ensure top-level permissions are not set to write-all"
# 	FAILED for resource: on(mega-linter)
# 	File: /.github/workflows/mega-linter.yml:6-7
# REPOSITORY_CHECKOV_DISABLE_ERRORS: true
