# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

APPLY_FIXES: all
DISABLE:
  - REPOSITORY_CHECKOV
#  - SPELL # Uncomment to disable checks of spelling mistakes
# PYTHON_PYRIGHT_DISABLE_ERRORS: true
# SPELL_CSPELL_DISABLE_ERRORS: true
# PRINT_ALL_FILES: false
# SHOW_ELAPSED_TIME: true
EMAIL_REPORTER: false
FILEIO_REPORTER: false
# JSON_REPORTER: false
# GITHUB_STATUS_REPORTER: false
