---
# ~/.mega-linter.yml
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/configuration/ and in linters documentation

## FILTERS ##

# FILTER_REGEX_EXCLUDE: "\
# (?i)(\
# |megalinter-reports/.*\
# |\\.git/.*\
# )$"

## CONVERT ERRORS TO WARNINGS ##

# quiets:
#   Check: CKV2_GHA_1: "Ensure top-level permissions are not set to write-all"
# 	FAILED for resource: on(mega-linter)
# 	File: /.github/workflows/mega-linter.yml:6-7
REPOSITORY_CHECKOV_DISABLE_ERRORS: true

# quiets:
#   fatal: detected dubious ownership in repository at '/github/workspace/.git'
REPOSITORY_DEVSKIM_DISABLE_ERRORS: true

## COMMAND ARGUMENTS ##

PYTHON_MYPY_ARGUMENTS: '--install-types'

# REPOSITORY_DEVSKIM_ARGUMENTS:
#   - '--ignore-globs'
#   - '**/megalinter-reports/**,**/.git/**'

## GLOBAL SETTINGS ##

APPLY_FIXES: all
# Quiet logs:
# [GitHub Status Reporter] Error posting Status for JSONwith prettier: 403
# GitHub API response: {"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/commits/statuses#create-a-commit-status"}
# GITHUB_STATUS_REPORTER: true
# LOG_LEVEL: DEBUG
PRINT_ALL_FILES: true
PRINT_ALPACA: false
# causes validation to fail:
# PYRIGHT_PYTHON_FORCE_VERSION: 'latest'
SHOW_ELAPSED_TIME: true
