---
# ~/.github/linters/.hadolint.yaml

# Rules: https://github.com/hadolint/hadolint?tab=readme-ov-file#rules
ignored:
  # DL3018 warning: Pin versions in apk add. Instead of apk add <package> use apk add <package>=<version>.
  - DL3018
  # DL3006 warning: Always tag the version of an image explicitly
  - DL3006

# eof
