---
# ~/.github/linters/.yamllint.yml
# Docs: https://yamllint.readthedocs.io/en/stable/configuration.html
# ML:   https://megalinter.io/latest/descriptors/yaml_yamllint/
# MLT:  https://github.com/oxsecurity/megalinter/blob/main/TEMPLATES/.yamllint.yml

# For `default` and `relaxed` configurations, see:
# https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration

extends: relaxed
rules:
  new-lines:
    level: warning
    type: unix
  line-length:
    level: warning
    max: 132 # default: 80
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  comments:
    min-spaces-from-content: 1 # Used to follow prettier standard: https://github.com/prettier/prettier/pull/10926
  new-line-at-end-of-file: disable
  trailing-spaces: disable

# was:
# rules:
#   braces:
#     level: warning
#     min-spaces-inside: 0
#     max-spaces-inside: 0
#     min-spaces-inside-empty: 1
#     max-spaces-inside-empty: 5
#   brackets:
#     level: warning
#     min-spaces-inside: 0
#     max-spaces-inside: 0
#     min-spaces-inside-empty: 1
#     max-spaces-inside-empty: 5
#   colons:
#     level: warning
#     max-spaces-before: 0
#     max-spaces-after: 1
#   commas:
#     level: warning
#     max-spaces-before: 0
#     min-spaces-after: 1
#     max-spaces-after: 1
#   comments: disable
#   comments-indentation: disable
#   document-end: disable
#   # disabled by @rasa for now:
#   document-start: disable
#   #  level: warning
#   #  present: true
#   empty-lines:
#     level: warning
#     max: 2
#     max-start: 0
#     max-end: 0
#   hyphens:
#     level: warning
#     max-spaces-after: 1
#   indentation:
#     level: warning
#     spaces: consistent
#     indent-sequences: true
#     check-multi-line-strings: false
#   key-duplicates: enable
#   line-length:
#     level: warning
#     max: 132
#     allow-non-breakable-words: true
#     allow-non-breakable-inline-mappings: true
