---
# ~/.github/linters/.yamllint.yml
# Docs: https://yamllint.readthedocs.io/en/stable/configuration.html
# ML:   https://megalinter.io/latest/descriptors/yaml_yamllint/
# MLT:  https://github.com/oxsecurity/megalinter/blob/main/TEMPLATES/.yamllint.yml

# For `default` and `relaxed` configurations, see:
# https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration

extends: relaxed
rules:
  comments:
    min-spaces-from-content: 1 # Used to follow prettier standard: https://github.com/prettier/prettier/pull/10926
  colons:
    max-spaces-after: -1
  line-length:
    level: warning
    max: 132 # default: 80
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  new-line-at-end-of-file: disable
  new-lines:
    level: warning
    type: unix
  trailing-spaces: disable

