
# From https://github.com/ad-m/github-push-action#example-workflow-file
name: black

on:
  workflow_dispatch:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - name: STEP actions/setup-python@v2
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: STEP pip install black
      # if: steps.cache.outputs.cache-hit != 'true'
      run: |
          python -m pip install --upgrade pip
          pip install black

    - name: STEP actions/checkout@v2
      uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

    - name: STEP black *.py
      id: black
      run: black --config .github/linters/.python-black --check ./*.py && echo "::set-output name=changes::false" 
    - if: failure()
      run: black --config .github/linters/.python-black ./*.py && echo "::set-output name=changes::true" 

    - name: STEP git commit -m "black" -a
      if: steps.black.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "black" -a

    - name: STEP ad-m/github-push-action@master
      if: steps.black.outputs.changes == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
