---
# $schema https://json.schemastore.org/github-workflow.json
name: clean-logs

# permissions: write

"on": # quotes required by linter
  workflow_dispatch:
    inputs:
      # checkov:skip=CKV_GHA_7:The build output cannot be affected by user parameters...
      #repository:
      #  description: 'Name of repository (e.g., user/repo).'
      #  type: string
      #  required: true
      #  default: ${{ github.repository }}
      retain_days:
        description: 'Number of days.'
        required: false
        default: '30'
        type: string
      keep_minimum_runs:
        description: 'The minimum runs to keep for each workflow.'
        required: false
        default: '2'
        type: string
      delete_workflow_pattern:
        description: 'The name or filename of the workflow. if not set then it will target all workflows.'
        required: false
        type: string
      delete_workflow_by_state_pattern:
        description: 'Remove workflow by state: active, deleted, disabled_fork, disabled_inactivity, disabled_manually'
        required: false
        default: "All"
        type: choice
        options:
          - "All"
          - active
          - deleted
          - disabled_inactivity
          - disabled_manually
      delete_run_by_conclusion_pattern:
        description: 'Remove workflow by conclusion: action_required, cancelled, failure, skipped, success'
        required: false
        default: "All"
        type: choice
        options:
          - "All"
          - action_required
          - cancelled
          - failure
          - skipped
          - success
      dry_run:
        description: 'Only log actions, do not perform any delete operations.'
        required: false
        type: string

jobs:
  clean-logs:
    uses: rasa/workflows/.github/workflows/clean-logs.yaml@main
    with:
      # not needed:
      # token: ${{ secrets.GITHUB_TOKEN }}
      # doesn't work:
      # repository: ${{ github.repository }}
      retain_days: ${{ inputs.retain_days }}
      keep_minimum_runs: ${{ inputs.keep_minimum_runs }}
      delete_workflow_pattern: ${{ inputs.delete_workflow_pattern }}
      delete_workflow_by_state_pattern: ${{ inputs.delete_workflow_by_state_pattern }}
      delete_run_by_conclusion_pattern: ${{ inputs.delete_run_by_conclusion_pattern }}
      dry_run: ${{ inputs.dry_run }}


# eof
