---
# Copied from: rasa/dotfiles/.github/workflows/mega-linter.yml
# EDIT THE ABOVE FILE, NOT THIS COPY, OR YOUR CHANGES WILL BE LOST!
# $schema https://json.schemastore.org/github-workflow.json

name: mega-linter

"on": # quotes required by linter
  pull_request:
  push:
    paths:
      - "**/*"
      - "!.gitattributes"
      - "!.gitmodules"
    #  - ".editorconfig"
    #  - ".github/**/*"
    #  - "!**.md"
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    inputs:
      # checkov:skip=CKV_GHA_7:The build output cannot be affected by user parameters...
      fetch_depth:
        description: Number of commits to fetch. 0 indicates all history for all branches and tags.
        type: string
        default: "1"
      # checkov:skip=CKV_GHA_7:The build output cannot be affected by user parameters...
      # validate_all_codebase:
      #   description: Validate the entire code base
      #   type: choice
      #  options:
      #    - "false"
      #    - "true"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  job:
    name: USES rasa/workflows/.github/workflows/mega-linter.yml@main
    uses: rasa/workflows/.github/workflows/mega-linter.yml@main
    secrets: inherit
    with:
      fetch_depth: ${{ inputs.fetch_depth }}
      validate_all_codebase: "true"

#

# cSpell:ignore gitmodules, rasa
