---
# $schema https://json.schemastore.org/github-workflow.json
# doesn't work, so moved to ~/.github/linters/.checkov.yml
#checkov:skip=CKV2_GHA_1
# CKV2_GHA_1: "Ensure top-level permissions are not set to write-all"
name: mega-linter

# permissions: write

"on": # quotes required by linter
  workflow_dispatch:
    inputs:
      # checkov:skip=CKV_GHA_7:The build output cannot be affected by user parameters...
      fetch_depth:
        description: "Number of commits to fetch. 0 indicates all history for all branches and tags."
        type: string
        required: false
        default: '1'
      # checkov:skip=CKV_GHA_7:The build output cannot be affected by user parameters...
      validate_all_codebase:
        description: "Validate the entire code base"
        type: boolean
        required: false
        default: false

jobs:
  megalinter-job:
    uses: rasa/workflows/.github/workflows/mega-linter.yml@main
    secrets: inherit
    with:
      fetch_depth: ${{ inputs.fetch_depth }}
      validate_all_codebase: ${{ inputs.validate_all_codebase }}


# eof
