---
# $schema https://json.schemastore.org/github-workflow.json
# ~/.github/workflows/mega-linter.yml
name: mega-linter

"on": # quotes required by linter
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    inputs:
      # checkov:skip=CKV_GHA_7:The build output cannot be affected by user parameters...
      fetch_depth:
        description: "Number of commits to fetch. 0 indicates all history for all branches and tags."
        type: string
        required: false
        default: '1'
      # checkov:skip=CKV_GHA_7:The build output cannot be affected by user parameters...
      validate_all_codebase:
        description: "Validate the entire code base"
        type: boolean
        required: false
        default: false

jobs:
  job:
    uses: rasa/workflows/.github/workflows/mega-linter.yml@main
    secrets: inherit
    with:
      fetch_depth: ${{ inputs.fetch_depth }}
      validate_all_codebase: ${{ inputs.validate_all_codebase }}


# eof
