---
# $schema https://json.schemastore.org/github-workflow.json

name: scraper

permissions: read-all

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  #  types: [opened, synchronize, reopened]
  release:
    types: [published, created, edited]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    inputs:
      # checkov:skip=CKV_GHA_7
      log_level:
        description: Log level
        type: choice
        default: 'info' # doesn't work: ${{ env.log_level }}
        options:
          - debug
          - info
          - warning
          - error
          - critical
      # checkov:skip=CKV_GHA_7
      code:
        description: TOC Code
        type: string
        default: 'CIV' # doesn't work: ${{ env.code }}
      # checkov:skip=CKV_GHA_7
      division:
        description: Division
        type: string
        default: '4' # doesn't work: ${{ env.division }}
      # checkov:skip=CKV_GHA_7
      part:
        description: Part
        type: string
        default: '4' # doesn't work: ${{ env.part }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  INPUT_CODE: ${{ github.event.inputs.code || 'CIV' }}
  INPUT_DIVISION: ${{ github.event.inputs.division || '4' }}
  INPUT_PART: ${{ github.event.inputs.part || '4' }}
  INPUT_LOG_LEVEL: ${{ github.event.inputs.log_level || 'debug' }}

jobs:
  job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          # - '3.10'
          # - '3.11'
          # - '3.12'
          - '3.13'
    steps:
      - name: RUN apt install tidy wkhtmltopdf (via awalsh128/cache-apt-pkgs-action)
        uses: awalsh128/cache-apt-pkgs-action@v1.5.3
        with:
          packages: tidy wkhtmltopdf
          version: 1.0
          # Bump me ^ if you have added any new packages

      - name: RUN chromedriver
        run: |
          echo chromedriver --url-base=/wd/hub
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          # sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: USE actions/checkout@v4.2.2
        uses: actions/checkout@v4.2.2
        with:
          show-progress: false

      - name: USE actions/setup-python@v5.6.0
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: RUN pip install -r requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: RUN python scraper.py
        run:
          python scraper.py

      - name: USE actions/upload-artifact@v4.6.2
        uses: actions/upload-artifact@v4.6.2
        with:
          name: html-and-pdf-${{ matrix.python-version }}
          path: |
            html
            pdf
            !**/.gitignore

# cSpell:ignore chromedriver, Xvfb
