---
# $schema https://json.schemastore.org/github-workflow.json
#checkov:skip=CKV2_GHA_1:Ensure top-level permissions are not set to write-all

name: scraper

env:
  log_level: info
  code: CIV
  division: 4
  part: 4
  
"on":
  push:
  #  branches: [ master, main ] # $default-branch doesn't seem to work
  pull_request:
  #  types: [opened, synchronize, reopened]
  release:
    types: [published, created, edited]
  # schedule:
  #  # run at 15:23 UTC every day (8:23am PDT/UTC-7)
  #  - cron: '23 15 * * *'
  workflow_dispatch:
    inputs:
      log_level: #checkov:skip=CKV_GHA_7
        description: 'Log level'
        # required: true
        type: choice
        default: 'info' # doesn't work: ${{ env.log_level }}
        options:
        - debug
        - info
        - warning
        - error
        - critical
      division:
        description: 'Division'
        # required: false
        type: string
        default: 'CIV' # doesn't work: ${{ env.division }}
      code:
        description: 'TOC Code'
        # required: false
        type: string
        default: '4' # doesn't work: ${{ env.code }}
      part:
        description: 'Part'
        # required: false
        type: string
        default: '4' # doesn't work: ${{ env.part }}

jobs:
  scraper-job:
    runs-on: ubuntu-latest
    steps:
      - name: RUN apt install tidy wkhtmltopdf
        run: |
            sudo apt -y update
            sudo apt -y install tidy wkhtmltopdf

      - name: RUN chromedriver
        run: |
          echo chromedriver --url-base=/wd/hub &
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          # sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: USES actions/checkout@v3
        uses: actions/checkout@v3

      - name: USES actions/setup-python@v4
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies

      - name: RUN pip install -r requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: RUN python scraper.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_LOG_LEVEL: ${{ github.event.inputs.log_level || env.log_level }}
        run: |
          (set -o posix;set)
          python scraper.py "${{ github.event.inputs.division || env.division }}" "${{ github.event.inputs.part || env.part }}" "${{ github.event.inputs.code || env.code }}"

      - name: USES actions/upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: html and pdf
          path: |
            html
            pdf
            !**/.gitignore
