# https://canovasjm.netlify.app/2020/11/29/github-actions-run-a-python-script-on-schedule-and-commit-changes/

name: scraper

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [published, created, edited]
  # schedule:
  #  # run at 15:23 UTC every day (8:23am PDT/UTC-7)
  #  - cron: '23 15 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'info'
        type: choice
        options:
        - debug
        - info
        - warning
        - error
        - critical
      code:
        description: 'TOC Code'     
        required: true
        default: 'CIV'
      division:
        description: 'Division'     
        required: false
        default: '4'
      part:
        description: 'Part'     
        required: false
        default: '4'
jobs:
  scraper:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: |
            sudo apt -y update
            sudo apt -y install tidy wkhtmltopdf

      # https://github.com/marketplace/actions/setup-chromedriver#for-ubuntu-latest-macos-latest
      - name: setup chromedriver
        uses: nanasess/setup-chromedriver@v1
        # with:
            # Optional: do not specify to match Chrome's version
            # chromedriver-version: '88.0.4324.96'
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          # sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: run actions/checkout@v2
        uses: actions/checkout@v2

      # fails: https://github.com/rasa/scoop-directory/runs/4252997621?check_suite_focus=true#step:7:8
      # - name: run actions/cache@v2 - pip
      #  uses: actions/cache@v2
      #  id: pip
      #  with:
      #    path: ~/.cache/pip
      #    key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      #    restore-keys: |
      #      ${{ runner.os }}-pip-

      # causes errors, see
      # https://github.com/rasa/scoop-directory/runs/4265697748?check_suite_focus=true#step:6:1097
      # - name: run actions/cache@v2 - cache
      #   uses: actions/cache@v2
      #   id: cache
      #   with:
      #     path: cache
      #     key: ${{ runner.os }}-cache-${{ hashFiles('**/cache.pickle') }}
      #     restore-keys: |
      #       ${{ runner.os }}-cache-

      - name: run actions/setup-python@v2
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: run pip install -r requirements.txt
        # if: steps.pip.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run python scraper.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          (set -o posix;set)
          python scraper.py ${{ github.event.inputs.division }} ${{ github.event.inputs.part }} ${{ github.event.inputs.code }}
          # ./run.sh ${{ github.event.inputs.division }} ${{ github.event.inputs.part }} ${{ github.event.inputs.code }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: html and pdf
          path: |
            html
            pdf
            !**/.gitignore
          
      - name: run git commit -am "scrape update [ci skip]"
        if: false
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -am "scrape update [ci skip]"

      - name: run ad-m/github-push-action@v0.6.0
        if: false
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
